[book]
authors = ["Shivam, Naman Mishra"]
language = "en"
multilingual = false
src = "src"
title = "ROS-Noetic-Tutorials"

[output.html]
theme = "my-theme"
default-theme = "light"
preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = false
copy-fonts = true
no-section-label = false

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = false
copy-js = true
line-numbers = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true